/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vnua.k62cnpm.xdptpm.libmanage.ui.panel;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Menu;
import java.awt.MenuItem;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;

import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.UIManager;

import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;
import vnua.k62cnpm.xdptpm.libmanage.aboutus.AboutUsFrame;
import vnua.k62cnpm.xdptpm.libmanage.alllibmanager.User;
import vnua.k62cnpm.xdptpm.libmanage.ui.login.LogInFrame;
import vnua.k62cnpm.xdptpm.libmanage.ui.panel.menubar.BackgroundMenuBar;

/**
 *
 * @author Minh
 */
public class MainFrame extends javax.swing.JFrame {
	private MainPanel mp;
	private List<User> listUser;
	
    /**
     * Creates new form MainFrame
     */
	
    public MainFrame() {
    	setLayout(new CardLayout());
    	setLocation(150, 10);
    	setSize(1200, 790);
        setResizable(false);
        setTitle("Luong Dinh Cua Library Management System - Vietnam National University of Agriculture");
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        try {
            Image imgIcon = ImageIO.read(getClass().getResource("/resources/images/icon.png"));
            setIconImage(imgIcon);
            UIManager.setLookAndFeel("javax.swing.plaf.nimbus.NimbusLookAndFeel");
            
        } catch(Exception e){
            e.printStackTrace();
        }
//        addMenuBar();
        addComp();
        addEvent();
        
    }


	public MainFrame(List<User> list) {
		this.listUser = list;
	}


	private void addMenuBar() {
//		BackgroundMenuBar bmb = new BackgroundMenuBar();
//		bmb.setColor(new Color(63, 57, 47));
//		bmb.setSize(1200, 50);
//		MainFrame.this.setJMenuBar(bmb);
//		
	}


	private void addComp() {
		mp = new MainPanel(listUser);
		add(mp);
	}


	private void addEvent() {
        addWindowListener(new WindowAdapter() {
                        @Override
			public void windowClosing(WindowEvent e) {
				int rs = JOptionPane.showConfirmDialog(MainFrame.this, "Do you want to exit?", "Alert", JOptionPane.YES_NO_OPTION);
				if (rs == JOptionPane.YES_OPTION) {
					dispose();
				}
			}
		});
    }
    
    @Override
    public void paint(Graphics g) {
        super.paint(g); //To change body of generated methods, choose Tools | Templates.
        
    }
    
    
    
//    /**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

}
